// Add options in any order; they will be sorted alphabetically with "Other" last
const DENOMINATIONS_RAW = [
  "RCC – Roman Catholic Church",
  "ECC – Eastern Catholic Churches",
  "OCA – Orthodox Church in America",
  "GOARCH – Greek Orthodox Archdiocese of America",
  "AOCA – Antiochian Orthodox Christian Archdiocese",
  "ROCOR – Russian Orthodox Church Outside Russia",
  "SOC – Serbian Orthodox Church (USA)",
  "ROAA – Romanian Orthodox Archdiocese in the Americas",
  "ELCA – Evangelical Lutheran Church in America",
  "LCMS – Lutheran Church–Missouri Synod",
  "WELS – Wisconsin Evangelical Lutheran Synod",
  "NALC – North American Lutheran Church",
  "LCMC – Lutheran Congregations in Mission for Christ",
  "PC(USA) – Presbyterian Church (U.S.A.)",
  "PCA – Presbyterian Church in America",
  "ECO – Evangelical Covenant Order of Presbyterians",
  "ARP – Associate Reformed Presbyterian Church",
  "CRCNA – Christian Reformed Church in North America",
  "URCNA – United Reformed Churches in North America",
  "RPCNA – Reformed Presbyterian Church of North America",
  "TEC – The Episcopal Church",
  "ACNA – Anglican Church in North America",
  "UMC – United Methodist Church",
  "GMC – Global Methodist Church",
  "FMC – Free Methodist Church",
  "WC – Wesleyan Church",
  "Naz – Church of the Nazarene",
  "AME – African Methodist Episcopal Church",
  "AMEZ – African Methodist Episcopal Zion Church",
  "SBC – Southern Baptist Convention",
  "ABCUSA – American Baptist Churches USA",
  "NBCUSA – National Baptist Convention, USA",
  "NMBCA – National Missionary Baptist Convention of America",
  "PNBC – Progressive National Baptist Convention",
  "FWBC – Free Will Baptist Church",
  "CoC – Churches of Christ",
  "DOC – Christian Church (Disciples of Christ)",
  "CC/CoC – Christian Churches and Churches of Christ",
  "AG – Assemblies of God",
  "COGIC – Church of God in Christ",
  "COG-TN – Church of God (Cleveland, Tennessee)",
  "PHC – Pentecostal Holiness Church",
  "Foursquare – International Church of the Foursquare Gospel",
  "C&MA – Christian and Missionary Alliance",
  "ECC – Evangelical Covenant Church",
  "EFCA – Evangelical Free Church of America",
  "SA – Salvation Army",
  "SDA – Seventh-day Adventist Church",
  "ND – Non-Denominational (Structured Independent Churches)",
] as const;

const OTHER = "Other";

export const DENOMINATIONS = [
  ...[...DENOMINATIONS_RAW].sort((a, b) => a.localeCompare(b)),
  OTHER,
] as const;

export type Denomination = (typeof DENOMINATIONS_RAW)[number] | typeof OTHER;
